services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ddd_eductive
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FLASK_ENV: development
    depends_on:
      - db
  test:
      build: .
      command: pytest --maxfail=1 --disable-warnings -q
      volumes:
        - .:/app
        - ./src:/app/src
      environment:
        DATABASE_URL: ${DATABASE_URL}
      depends_on:
        - db

volumes:
  postgres_data: